plugins { id 'com.android.application' }

android {
    namespace 'com.a26.femalevoice'
    compileSdk 35
    defaultConfig {
        applicationId 'com.a26.femalevoice'
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
